"""Canonical DuckDB table contracts shared across engines."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class TableContract:
    """Immutable description of a managed table."""

    description: str
    columns: Dict[str, str]
    unique_key: List[str]
    storage_pattern: str
    fixture: Optional[str] = None


TABLE_CONTRACTS: Dict[str, TableContract] = {
    "market_data": TableContract(
        description="OHLCV bars fetched via connectors or ingested CSVs",
        storage_pattern="data/market/{source}/{symbol}/{interval}.parquet",
        unique_key=["symbol", "timestamp", "source", "interval"],
        columns={
            "timestamp": "TIMESTAMP",
            "symbol": "TEXT",
            "source": "TEXT",
            "interval": "TEXT",
            "open": "DOUBLE",
            "high": "DOUBLE",
            "low": "DOUBLE",
            "close": "DOUBLE",
            "volume": "DOUBLE",
            "vwap": "DOUBLE",
            "trades": "BIGINT",
            "data_hash": "TEXT",
            "created_at": "TIMESTAMP",
        },
        fixture="tests/fixtures/sample_market_data.csv",
    ),
    "news_data": TableContract(
        description="Normalized RSS or news documents",
        storage_pattern="data/news/{source}/{year}/{month}.parquet",
        unique_key=["link", "timestamp"],
        columns={
            "timestamp": "TIMESTAMP",
            "source": "TEXT",
            "category": "TEXT",
            "title": "TEXT",
            "link": "TEXT",
            "description": "TEXT",
            "author": "TEXT",
            "tags": "TEXT[]",
            "content_hash": "TEXT",
            "created_at": "TIMESTAMP",
        },
        fixture="tests/fixtures/pipeline/news_sample.parquet",
    ),
    "analysis_data": TableContract(
        description="Outputs from analytics/ML models (FinBERT, etc.)",
        storage_pattern="data/analysis/{analysis_type}/{symbol}/{timestamp}.parquet",
        unique_key=["symbol", "timestamp", "analysis_type", "model_version"],
        columns={
            "timestamp": "TIMESTAMP",
            "symbol": "TEXT",
            "analysis_type": "TEXT",
            "model_name": "TEXT",
            "model_version": "TEXT",
            "prediction": "DOUBLE",
            "confidence": "DOUBLE",
            "features": "JSON",
            "metadata": "JSON",
            "created_at": "TIMESTAMP",
        },
        fixture="tests/fixtures/pipeline/sentiment_sample.parquet",
    ),
    "metrics_data": TableContract(
        description="Aggregated KPIs generated by trackers",
        storage_pattern="data/metrics/{metric_type}/{symbol}.parquet",
        unique_key=["symbol", "timestamp", "metric_type"],
        columns={
            "timestamp": "TIMESTAMP",
            "symbol": "TEXT",
            "metric_type": "TEXT",
            "metric_name": "TEXT",
            "value": "DOUBLE",
            "period": "TEXT",
            "metadata": "JSON",
            "created_at": "TIMESTAMP",
        },
    ),
}


def get_contract(table_name: str) -> TableContract:
    """Return the contract for the requested table."""

    try:
        return TABLE_CONTRACTS[table_name]
    except KeyError as exc:
        raise KeyError(f"Unknown table '{table_name}'. Available: {list(TABLE_CONTRACTS)}") from exc